# Generated by Django 4.0.2 on 2022-02-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(max_length=10)),
                ('currentCount', models.IntegerField()),
                ('message', models.TextField()),
                ('channelId', models.CharField(max_length=25)),
                ('sended', models.BooleanField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.phone')),
            ],
        ),
    ]
