# Generated by Django 4.0.2 on 2022-03-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senttelegrammessage',
            options={'verbose_name': '텔레그램 메시지', 'verbose_name_plural': '텔레그램 메시지'},
        ),
        migrations.AlterField(
            model_name='senttelegrammessage',
            name='chat_text',
            field=models.TextField(blank=True, null=True, verbose_name='내용'),
        ),
    ]
