# Generated by Django 4.0.2 on 2022-02-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '센터정보',
                'verbose_name_plural': '센터정보',
            },
        ),
        migrations.CreateModel(
            name='LowThroughput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkId', models.CharField(blank=True, choices=[('DL', 'DL'), ('UP', 'UL')], max_length=10, null=True, verbose_name='단말유형')),
                ('dataType', models.CharField(choices=[('DL', 'DL'), ('UP', 'UL')], max_length=10, verbose_name='데이터유형')),
                ('bandwidth', models.FloatField(default=0.0, null=True, verbose_name='속도')),
            ],
            options={
                'verbose_name': '속도저하 기준',
                'verbose_name_plural': '속도저하 기준',
            },
        ),
        migrations.CreateModel(
            name='Morphology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userInfo2', models.CharField(blank=True, max_length=100, null=True, verbose_name='모폴러지')),
                ('morphology', models.CharField(blank=True, max_length=100, null=True, verbose_name='모폴러지')),
            ],
            options={
                'verbose_name': '모폴러지',
                'verbose_name_plural': '모폴러지',
            },
        ),
    ]
