# Generated by Django 4.0.2 on 2022-03-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendfailure',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='management.center', verbose_name='센터'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='networkId',
            field=models.CharField(blank=True, choices=[('WiFi', 'WiFi'), ('5G', '5G'), ('LTE', 'LTE'), ('3G', '3G')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.AlterField(
            model_name='morphology',
            name='morphology',
            field=models.CharField(blank=True, choices=[('취약지구', '취약지구'), ('행정동', '행정동'), ('테마', '테마'), ('커버리지', '커버리지'), ('인빌딩', '인빌딩')], max_length=100, null=True, verbose_name='모폴러지'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='networkId',
            field=models.CharField(blank=True, choices=[('WiFi', 'WiFi'), ('5G', '5G'), ('LTE', 'LTE'), ('3G', '3G')], max_length=10, null=True, verbose_name='단말유형'),
        ),
    ]
