# Generated by Django 4.0.2 on 2022-03-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowthroughput',
            name='networkId',
            field=models.CharField(blank=True, choices=[('LTE', 'LTE'), ('5G', '5G'), ('3G', '3G'), ('WiFi', 'WiFi')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.AlterField(
            model_name='morphologymap',
            name='wordsCond',
            field=models.CharField(blank=True, choices=[('포함단어', '포함단어'), ('시작단어', '시작단어')], max_length=20, null=True, verbose_name='조건'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='networkId',
            field=models.CharField(blank=True, choices=[('LTE', 'LTE'), ('5G', '5G'), ('3G', '3G'), ('WiFi', 'WiFi')], max_length=10, null=True, verbose_name='단말유형'),
        ),
    ]
