# Generated by Django 4.0.2 on 2022-03-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowthroughput',
            name='areaInd',
            field=models.CharField(choices=[('NORM', '보통지역'), ('WEEK', '취약지역')], max_length=10, verbose_name='지역구분'),
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='dataType',
            field=models.CharField(choices=[('DL', 'DL'), ('UL', 'UL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='networkId',
            field=models.CharField(blank=True, choices=[('WiFi', 'WiFi'), ('3G', '3G'), ('5G', '5G'), ('LTE', 'LTE')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.AlterField(
            model_name='morphology',
            name='morphology',
            field=models.CharField(blank=True, choices=[('커버리지', '커버리지'), ('행정동', '행정동'), ('테마', '테마'), ('인빌딩', '인빌딩'), ('취약지구', '취약지구')], max_length=100, null=True, verbose_name='모폴러지'),
        ),
        migrations.AlterField(
            model_name='morphology',
            name='wordsCond',
            field=models.CharField(blank=True, choices=[('시작단어', '시작단어'), ('포함단어', '포함단어')], max_length=20, null=True, verbose_name='조건'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='areaInd',
            field=models.CharField(choices=[('NORM', '보통지역'), ('WEEK', '취약지역')], max_length=10, verbose_name='지역구분'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='dataType',
            field=models.CharField(choices=[('DL', 'DL'), ('UL', 'UL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='networkId',
            field=models.CharField(blank=True, choices=[('WiFi', 'WiFi'), ('3G', '3G'), ('5G', '5G'), ('LTE', 'LTE')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.CreateModel(
            name='ReportCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportCycle', models.CharField(max_length=100, verbose_name='보고주기')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.center', verbose_name='센터')),
            ],
            options={
                'verbose_name': '측정 보고주기',
                'verbose_name_plural': '측정 보고주기',
            },
        ),
    ]
