# Generated by Django 4.0.2 on 2022-03-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='morph_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userInfo_sort', models.CharField(blank=True, choices=[('userInfo2', 'userInfo2')], max_length=100, null=True, verbose_name='구분')),
                ('words_cond', models.CharField(blank=True, choices=[('포함단어', '포함단어'), ('시작단어', '시작단어')], max_length=20, null=True, verbose_name='조건')),
                ('words', models.CharField(blank=True, max_length=200, null=True, verbose_name='단어')),
                ('morph', models.CharField(blank=True, choices=[('커버리지', '커버리지'), ('테마', '테마'), ('취약지구', '취약지구'), ('행정동', '행정동'), ('인빌딩', '인빌딩')], max_length=100, null=True, verbose_name='모폴러지')),
                ('manage', models.BooleanField(default=False, verbose_name='관리대상')),
            ],
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='dataType',
            field=models.CharField(choices=[('UL', 'UL'), ('DL', 'DL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='networkId',
            field=models.CharField(blank=True, choices=[('LTE', 'LTE'), ('WiFi', 'WiFi'), ('3G', '3G'), ('5G', '5G')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.AlterField(
            model_name='morphology',
            name='morphology',
            field=models.CharField(blank=True, choices=[('커버리지', '커버리지'), ('테마', '테마'), ('취약지구', '취약지구'), ('행정동', '행정동'), ('인빌딩', '인빌딩')], max_length=100, null=True, verbose_name='모폴러지'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='dataType',
            field=models.CharField(choices=[('UL', 'UL'), ('DL', 'DL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='networkId',
            field=models.CharField(blank=True, choices=[('LTE', 'LTE'), ('WiFi', 'WiFi'), ('3G', '3G'), ('5G', '5G')], max_length=10, null=True, verbose_name='단말유형'),
        ),
    ]
