# Generated by Django 4.0.2 on 2022-03-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_lowthroughput_datatype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowthroughput',
            name='dataType',
            field=models.CharField(choices=[('DL', 'DL'), ('UL', 'UL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='networkId',
            field=models.CharField(blank=True, choices=[('WiFi', 'WiFi'), ('LTE', 'LTE'), ('5G', '5G'), ('3G', '3G')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.AlterField(
            model_name='morphologymap',
            name='wordsCond',
            field=models.CharField(blank=True, choices=[('포함단어', '포함단어'), ('시작단어', '시작단어')], max_length=20, null=True, verbose_name='조건'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='dataType',
            field=models.CharField(choices=[('DL', 'DL'), ('UL', 'UL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='networkId',
            field=models.CharField(blank=True, choices=[('WiFi', 'WiFi'), ('LTE', 'LTE'), ('5G', '5G'), ('3G', '3G')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.CreateModel(
            name='CenterManageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siDo', models.CharField(blank=True, max_length=100, null=True, verbose_name='시,도')),
                ('guGun', models.CharField(blank=True, max_length=100, null=True, verbose_name='구,군')),
                ('eupDong', models.CharField(blank=True, max_length=100, null=True, verbose_name='읍,면,동')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소상세')),
                ('addrType', models.CharField(blank=True, max_length=50, null=True, verbose_name='도시유형')),
                ('bonbu', models.CharField(blank=True, max_length=50, null=True, verbose_name='본부')),
                ('opCenter', models.CharField(blank=True, max_length=50, null=True, verbose_name='운용센터')),
                ('team', models.CharField(blank=True, max_length=50, null=True, verbose_name='부서')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.center', verbose_name='센터')),
            ],
            options={
                'verbose_name': '센터별 관할구역',
                'verbose_name_plural': '센터별 관할구역',
            },
        ),
    ]
