# Generated by Django 4.0.2 on 2022-03-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_morph_set_alter_lowthroughput_datatype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='morph_set',
        ),
        migrations.AddField(
            model_name='morphology',
            name='manage',
            field=models.BooleanField(default=False, verbose_name='관리대상'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='words',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='단어'),
        ),
        migrations.AddField(
            model_name='morphology',
            name='wordsCond',
            field=models.CharField(blank=True, choices=[('시작단어', '시작단어'), ('포함단어', '포함단어')], max_length=20, null=True, verbose_name='조건'),
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='dataType',
            field=models.CharField(choices=[('DL', 'DL'), ('UL', 'UL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='networkId',
            field=models.CharField(blank=True, choices=[('LTE', 'LTE'), ('3G', '3G'), ('WiFi', 'WiFi'), ('5G', '5G')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.AlterField(
            model_name='morphology',
            name='morphology',
            field=models.CharField(blank=True, choices=[('테마', '테마'), ('행정동', '행정동'), ('취약지구', '취약지구'), ('인빌딩', '인빌딩'), ('커버리지', '커버리지')], max_length=100, null=True, verbose_name='모폴러지'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='dataType',
            field=models.CharField(choices=[('DL', 'DL'), ('UL', 'UL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='networkId',
            field=models.CharField(blank=True, choices=[('LTE', 'LTE'), ('3G', '3G'), ('WiFi', 'WiFi'), ('5G', '5G')], max_length=10, null=True, verbose_name='단말유형'),
        ),
    ]
