# Generated by Django 4.0.2 on 2022-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_lowthroughput_areaind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowthroughput',
            name='areaInd',
            field=models.CharField(choices=[('WEEK', '취약지역'), ('NORM', '보통지역')], max_length=10, verbose_name='지역구분'),
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='networkId',
            field=models.CharField(blank=True, choices=[('5G', '5G'), ('WiFi', 'WiFi'), ('3G', '3G'), ('LTE', 'LTE')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='areaInd',
            field=models.CharField(choices=[('WEEK', '취약지역'), ('NORM', '보통지역')], max_length=10, verbose_name='지역구분'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='networkId',
            field=models.CharField(blank=True, choices=[('5G', '5G'), ('WiFi', 'WiFi'), ('3G', '3G'), ('LTE', 'LTE')], max_length=10, null=True, verbose_name='단말유형'),
        ),
    ]
