# Generated by Django 4.0.2 on 2022-03-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_lowthroughput_datatype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowthroughput',
            name='areaInd',
            field=models.CharField(choices=[('NORM', '보통지역'), ('WEEK', '취약지역')], max_length=10, verbose_name='지역구분'),
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='networkId',
            field=models.CharField(blank=True, choices=[('5G', '5G'), ('3G', '3G'), ('LTE', 'LTE'), ('WiFi', 'WiFi')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='areaInd',
            field=models.CharField(choices=[('NORM', '보통지역'), ('WEEK', '취약지역')], max_length=10, verbose_name='지역구분'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='networkId',
            field=models.CharField(blank=True, choices=[('5G', '5G'), ('3G', '3G'), ('LTE', 'LTE'), ('WiFi', 'WiFi')], max_length=10, null=True, verbose_name='단말유형'),
        ),
    ]
