# Generated by Django 4.0.2 on 2022-03-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_lowthroughput_datatype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowthroughput',
            name='dataType',
            field=models.CharField(choices=[('UL', 'UL'), ('DL', 'DL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='networkId',
            field=models.CharField(blank=True, choices=[('LTE', 'LTE'), ('3G', '3G'), ('WiFi', 'WiFi'), ('5G', '5G')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='dataType',
            field=models.CharField(choices=[('UL', 'UL'), ('DL', 'DL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='networkId',
            field=models.CharField(blank=True, choices=[('LTE', 'LTE'), ('3G', '3G'), ('WiFi', 'WiFi'), ('5G', '5G')], max_length=10, null=True, verbose_name='단말유형'),
        ),
    ]
