# Generated by Django 4.0.2 on 2022-03-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_lowthroughput_areaind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowthroughput',
            name='dataType',
            field=models.CharField(choices=[('DL', 'DL'), ('UL', 'UL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='lowthroughput',
            name='networkId',
            field=models.CharField(blank=True, choices=[('3G', '3G'), ('5G', '5G'), ('WiFi', 'WiFi'), ('LTE', 'LTE')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='dataType',
            field=models.CharField(choices=[('DL', 'DL'), ('UL', 'UL')], max_length=10, verbose_name='데이터유형'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='networkId',
            field=models.CharField(blank=True, choices=[('3G', '3G'), ('5G', '5G'), ('WiFi', 'WiFi'), ('LTE', 'LTE')], max_length=10, null=True, verbose_name='단말유형'),
        ),
    ]
