# Generated by Django 4.0.2 on 2022-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_lowthroughput_areaind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowthroughput',
            name='networkId',
            field=models.CharField(blank=True, choices=[('5G', '5G'), ('WiFi', 'WiFi'), ('3G', '3G'), ('LTE', 'LTE')], max_length=10, null=True, verbose_name='단말유형'),
        ),
        migrations.AlterField(
            model_name='morphology',
            name='morphology',
            field=models.CharField(blank=True, choices=[('취약지구', '취약지구'), ('커버리지', '커버리지'), ('테마', '테마'), ('인빌딩', '인빌딩'), ('행정동', '행정동')], max_length=100, null=True, verbose_name='모폴러지'),
        ),
        migrations.AlterField(
            model_name='sendfailure',
            name='networkId',
            field=models.CharField(blank=True, choices=[('5G', '5G'), ('WiFi', 'WiFi'), ('3G', '3G'), ('LTE', 'LTE')], max_length=10, null=True, verbose_name='단말유형'),
        ),
    ]
