# Generated by Django 4.0.1 on 2022-02-17 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.BigIntegerField()),
                ('avg_downloadTransfer', models.FloatField()),
                ('avg_uploadTransfer', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('total_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measuredata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neworkid', models.CharField(max_length=10)),
                ('meastime', models.BigIntegerField()),
                ('downloadTransfer', models.IntegerField()),
                ('uploadTransfer', models.IntegerField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.phone')),
            ],
        ),
    ]
