# Generated by Django 4.0.2 on 2022-02-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.BigIntegerField()),
                ('avg_downloadBandwidth', models.FloatField()),
                ('avg_uploadBandwidth', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('total_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(max_length=10)),
                ('currentCount', models.IntegerField()),
                ('message', models.TextField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.phone')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureSecondData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.BigIntegerField()),
                ('neworkid', models.CharField(max_length=10)),
                ('meastime', models.BigIntegerField()),
                ('currentCount', models.IntegerField()),
                ('downloadBandwidth', models.FloatField()),
                ('uploadBandwidth', models.FloatField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.phone')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureCallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.BigIntegerField()),
                ('neworkid', models.CharField(max_length=10)),
                ('meastime', models.BigIntegerField()),
                ('currentCount', models.IntegerField()),
                ('downloadBandwidth', models.FloatField()),
                ('uploadBandwidth', models.FloatField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitor.phone')),
            ],
        ),
    ]
