# Generated by Django 4.0.2 on 2022-03-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='morph2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='모폴러지2'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ispId',
            field=models.CharField(blank=True, choices=[('45006', 'LGU+'), ('45005', 'SKT'), ('45008', 'KT')], max_length=10, null=True, verbose_name='통신사'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='morphology',
            field=models.CharField(blank=True, choices=[('커버리지', '커버리지'), ('테마', '테마'), ('취약지구', '취약지구'), ('행정동', '행정동'), ('인빌딩', '인빌딩')], max_length=100, null=True, verbose_name='모폴러지'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('END', '측정종료'), ('POWERON', 'PowerOn'), ('MEASURING', '측정중'), ('START', '측정시작')], max_length=10, null=True, verbose_name='진행단계'),
        ),
    ]
