# Generated by Django 4.0.2 on 2022-03-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurecalldata',
            name='currentCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='콜카운트'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ispId',
            field=models.CharField(blank=True, choices=[('45006', 'LGU+'), ('45008', 'KT'), ('45005', 'SKT')], max_length=10, null=True, verbose_name='통신사'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='measdate',
            field=models.CharField(max_length=10, verbose_name='측정일자'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('POWERON', 'PowerOn'), ('MEASURING', '측정중'), ('START', '측정시작'), ('END', '측정종료')], max_length=10, null=True, verbose_name='진행단계'),
        ),
        migrations.AlterField(
            model_name='phonegroup',
            name='ispId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
