# Generated by Django 4.0.2 on 2022-03-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ispId',
            field=models.CharField(blank=True, choices=[('45005', 'SKT'), ('45008', 'KT'), ('45006', 'LGU+')], max_length=10, null=True, verbose_name='통신사'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('START_M', '측정시작'), ('END', '측정종료'), ('START_F', '측정시작'), ('POWERON', 'PowerOn'), ('MEASURING', '측정중')], max_length=10, null=True, verbose_name='진행단계'),
        ),
        migrations.AlterField(
            model_name='phonegroup',
            name='ispId',
            field=models.CharField(blank=True, choices=[('45005', 'SKT'), ('45008', 'KT'), ('45006', 'LGU+')], max_length=10, null=True, verbose_name='통신사'),
        ),
    ]
