# Generated by Django 4.0.2 on 2022-02-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measureseconddata',
            name='before_lat',
        ),
        migrations.RemoveField(
            model_name='measureseconddata',
            name='before_lon',
        ),
    ]
