# Generated by Django 4.0.2 on 2022-02-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_measurecalldata_ispid_measureseconddata_ispid'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurecalldata',
            name='userInfo2',
            field=models.CharField(default='행-용택-1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measureseconddata',
            name='userInfo2',
            field=models.CharField(default='행-용택-1', max_length=100),
            preserve_default=False,
        ),
    ]
