# Generated by Django 4.0.2 on 2022-03-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_phone_morph2_alter_phone_ispid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='morph2',
        ),
        migrations.AlterField(
            model_name='phone',
            name='ispId',
            field=models.CharField(blank=True, choices=[('45006', 'LGU+'), ('45008', 'KT'), ('45005', 'SKT')], max_length=10, null=True, verbose_name='통신사'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='morphology',
            field=models.CharField(blank=True, choices=[('커버리지', '커버리지'), ('인빌딩', '인빌딩'), ('취약지구', '취약지구'), ('테마', '테마'), ('행정동', '행정동')], max_length=100, null=True, verbose_name='모폴러지'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('MEASURING', '측정중'), ('END', '측정종료'), ('START', '측정시작'), ('POWERON', 'PowerOn')], max_length=10, null=True, verbose_name='진행단계'),
        ),
    ]
