# Generated by Django 4.0.2 on 2022-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_measurecalldata_currentcount_alter_phone_ispid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ispId',
            field=models.CharField(blank=True, choices=[('45008', 'KT'), ('45005', 'SKT'), ('45006', 'LGU+')], max_length=10, null=True, verbose_name='통신사'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('START', '측정시작'), ('POWERON', 'PowerOn'), ('MEASURING', '측정중'), ('END', '측정종료')], max_length=10, null=True, verbose_name='진행단계'),
        ),
    ]
