# Generated by Django 4.0.2 on 2022-03-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_phone_morph2_alter_phone_ispid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ispId',
            field=models.CharField(blank=True, choices=[('45008', 'KT'), ('45006', 'LGU+'), ('45005', 'SKT')], max_length=10, null=True, verbose_name='통신사'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='morphology',
            field=models.CharField(blank=True, choices=[('행정동', '행정동'), ('취약지구', '취약지구'), ('테마', '테마'), ('커버리지', '커버리지'), ('인빌딩', '인빌딩')], max_length=100, null=True, verbose_name='모폴러지'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('START', '측정시작'), ('END', '측정종료'), ('MEASURING', '측정중'), ('POWERON', 'PowerOn')], max_length=10, null=True, verbose_name='진행단계'),
        ),
    ]
