# Generated by Django 4.0.2 on 2022-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_phone_ispid_alter_phone_morphology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ispId',
            field=models.CharField(blank=True, choices=[('45005', 'SKT'), ('45008', 'KT'), ('45006', 'LGU+')], max_length=10, null=True, verbose_name='통신사'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='morphology',
            field=models.CharField(blank=True, choices=[('취약지구', '취약지구'), ('커버리지', '커버리지'), ('테마', '테마'), ('인빌딩', '인빌딩'), ('행정동', '행정동')], max_length=100, null=True, verbose_name='모폴러지'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('END', '측정종료'), ('START', '측정시작'), ('MEASURING', '측정중'), ('POWERON', 'PowerOn')], max_length=10, null=True, verbose_name='진행단계'),
        ),
    ]
