<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-12 01:43
=======
# Generated by Django 4.0.2 on 2022-03-14 09:33
>>>>>>> 0f277551f46bb7d33cd5d5a5e6c3cfaf6273b726

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, null=True)),
                ('networkId', models.CharField(blank=True, choices=[('LTE', 'LTE'), ('WiFi', 'WiFi+'), ('품질취약지역', '품질취약지역'), ('5G', '5G')], max_length=30, null=True)),
                ('area', models.CharField(blank=True, choices=[('해안도로', '해안도로'), ('여객항로', '여객항로'), ('다중이용시설/교통인프라', '다중이용시설/교통인프라'), ('개방', '개방'), ('유인도서', '유인도서'), ('커버리지', '커버리지'), ('행정동', '행정동'), ('등산로', '등산로'), ('상용', '상용')], max_length=30, null=True)),
                ('molph_level0', models.CharField(blank=True, choices=[('대도시', '대도시'), ('테마', '테마'), ('농어촌', '농어촌'), ('인빌딩', '인빌딩'), ('중소도시', '중소도시')], max_length=30, null=True)),
                ('meas_count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('dong', models.IntegerField(default=0, null=True)),
                ('dagyo', models.IntegerField(default=0, null=True)),
                ('coverage5g', models.IntegerField(default=0, null=True)),
                ('bigct', models.IntegerField(default=0, null=True)),
                ('smallct', models.IntegerField(default=0, null=True)),
                ('nong', models.IntegerField(default=0, null=True)),
                ('inbuiling', models.IntegerField(default=0, null=True)),
                ('theme', models.IntegerField(default=0, null=True)),
                ('coveragelte', models.IntegerField(default=0, null=True)),
                ('sangyong', models.IntegerField(default=0, null=True)),
                ('gaebang', models.IntegerField(default=0, null=True)),
                ('mountain', models.IntegerField(default=0, null=True)),
                ('ship', models.IntegerField(default=0, null=True)),
                ('yooin', models.IntegerField(default=0, null=True)),
                ('searoad', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodayRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('jiyok', models.CharField(blank=True, max_length=10, null=True)),
<<<<<<< HEAD
                ('date', models.DateField(blank=True, default=datetime.date(2022, 3, 12))),
=======
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
>>>>>>> 0f277551f46bb7d33cd5d5a5e6c3cfaf6273b726
                ('dongdaco', models.CharField(blank=True, max_length=30, null=True)),
                ('bigsmallnongintheme', models.CharField(blank=True, max_length=10, null=True)),
                ('sanggae', models.CharField(blank=True, max_length=10, null=True)),
                ('weakjiyok', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
