# Generated by Django 4.0.2 on 2022-03-12 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('dong', models.IntegerField(default=0, null=True)),
                ('dagyo', models.IntegerField(default=0, null=True)),
                ('coverage5g', models.IntegerField(default=0, null=True)),
                ('bigct', models.IntegerField(default=0, null=True)),
                ('smallct', models.IntegerField(default=0, null=True)),
                ('nong', models.IntegerField(default=0, null=True)),
                ('inbuiling', models.IntegerField(default=0, null=True)),
                ('theme', models.IntegerField(default=0, null=True)),
                ('coveragelte', models.IntegerField(default=0, null=True)),
                ('sangyong', models.IntegerField(default=0, null=True)),
                ('gaebang', models.IntegerField(default=0, null=True)),
                ('mountain', models.IntegerField(default=0, null=True)),
                ('ship', models.IntegerField(default=0, null=True)),
                ('yooin', models.IntegerField(default=0, null=True)),
                ('searoad', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodayRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('jiyok', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date(2022, 3, 12))),
                ('dongdaco', models.CharField(blank=True, max_length=30, null=True)),
                ('bigsmallnongintheme', models.CharField(blank=True, max_length=10, null=True)),
                ('sanggae', models.CharField(blank=True, max_length=10, null=True)),
                ('weakjiyok', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
