# Generated by Django 4.0.2 on 2022-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('dong', models.IntegerField(default=0, null=True)),
                ('dagyo', models.IntegerField(default=0, null=True)),
                ('coverage', models.IntegerField(default=0, null=True)),
                ('bigct', models.IntegerField(default=0, null=True)),
                ('smallct', models.IntegerField(default=0, null=True)),
                ('inbuiling', models.IntegerField(default=0, null=True)),
                ('nong', models.IntegerField(default=0, null=True)),
                ('theme', models.IntegerField(default=0, null=True)),
                ('sangyong', models.IntegerField(default=0, null=True)),
                ('gaebang', models.IntegerField(default=0, null=True)),
                ('mountain', models.IntegerField(default=0, null=True)),
                ('ship', models.IntegerField(default=0, null=True)),
                ('yooin', models.IntegerField(default=0, null=True)),
                ('searoad', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
