# Generated by Django 4.0.2 on 2022-03-15 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='측정일자를 반드시 입력해야 합니다.', verbose_name='측정일자')),
                ('info', models.CharField(blank=True, help_text='측정정보를 적어주세요.', max_length=30, null=True, verbose_name='측정정보')),
                ('networkId', models.CharField(blank=True, choices=[('5G', '5G'), ('LTE', 'LTE'), ('WiFi', 'WiFi'), ('품질취약지역', '품질취약지역')], help_text='측정 네트워크를 선택해주세요.', max_length=30, null=True, verbose_name='네트워크구분')),
                ('area', models.CharField(blank=True, choices=[('3.커버리지', '커버리지'), ('5.개방', '개방'), ('2.다중이용시설/교통인프라', '다중이용시설/교통인프라'), ('9.해안도로', '해안도로'), ('6.등산로', '등산로'), ('4.상용', '상용'), ('8.유인도서', '유인도서'), ('1.행정동', '행정동'), ('7.여객항로', '여객항로')], help_text='측정위치 구분자 선택해주세요.', max_length=30, null=True, verbose_name='측정위치')),
                ('molph_level0', models.CharField(blank=True, choices=[('5.테마', '테마'), ('4.인빌딩', '인빌딩'), ('2.중소도시', '중소도시'), ('3.농어촌', '농어촌'), ('1.대도시', '대도시')], help_text='측정위치1 구분자 선택해주세요.', max_length=30, null=True, verbose_name='측정위치1')),
                ('molph_level1', models.CharField(blank=True, help_text='측정지역을 적어주세요.', max_length=30, null=True, verbose_name='지역')),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='bigct',
            new_name='area1',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='coverage5g',
            new_name='area10',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='coveragelte',
            new_name='area11',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='dagyo',
            new_name='area12',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='dong',
            new_name='area13',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='gaebang',
            new_name='area14',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='inbuiling',
            new_name='area15',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='mountain',
            new_name='area2',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='nong',
            new_name='area3',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='sangyong',
            new_name='area4',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='searoad',
            new_name='area5',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='smallct',
            new_name='area6',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='ship',
            new_name='area7',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='theme',
            new_name='area8',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='yooin',
            new_name='area9',
        ),
        migrations.RemoveField(
            model_name='register',
            name='category',
        ),
        migrations.AddField(
            model_name='register',
            name='planYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='total5G',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='totalLTE',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='totalWeakArea',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='totalWiFi',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='measplan',
            name='area',
            field=models.CharField(blank=True, choices=[('3.커버리지', '커버리지'), ('5.개방', '개방'), ('2.다중이용시설/교통인프라', '다중이용시설/교통인프라'), ('9.해안도로', '해안도로'), ('6.등산로', '등산로'), ('4.상용', '상용'), ('8.유인도서', '유인도서'), ('1.행정동', '행정동'), ('7.여객항로', '여객항로')], help_text='측정위치 구분자 선택해주세요.', max_length=30, null=True, verbose_name='측정위치'),
        ),
        migrations.AlterField(
            model_name='measplan',
            name='molph_level0',
            field=models.CharField(blank=True, choices=[('5.테마', '테마'), ('4.인빌딩', '인빌딩'), ('2.중소도시', '중소도시'), ('3.농어촌', '농어촌'), ('1.대도시', '대도시')], help_text='측정위치1 구분자 선택해주세요.', max_length=30, null=True, verbose_name='측정위치1'),
        ),
        migrations.AlterField(
            model_name='measplan',
            name='networkId',
            field=models.CharField(blank=True, choices=[('WiFi', 'WiFi+'), ('5G', '5G'), ('LTE', 'LTE'), ('품질취약지역', '품질취약지역')], help_text='측정 네트워크를 선택해주세요.', max_length=30, null=True, verbose_name='네트워크구분'),
        ),
        migrations.AlterField(
            model_name='measplan',
            name='year',
            field=models.IntegerField(default=0, help_text='대상년도를 입력해주세요.', null=True, verbose_name='대상년도'),
        ),
    ]
