# Generated by Django 4.0.2 on 2022-02-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_register_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='category',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
