# Generated by Django 4.0.2 on 2022-02-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_register_dong'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
