# Generated by Django 4.0.2 on 2022-03-08 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_todayregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayregister',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 8)),
        ),
    ]
