# Generated by Django 4.0.2 on 2022-04-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logger_name', models.CharField(max_length=100, verbose_name='로그명')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'NotSet'), (20, 'Info'), (30, 'Warning'), (10, 'Debug'), (40, 'Error'), (50, 'Fatal')], db_index=True, default=40, verbose_name='로그레벨')),
                ('msg', models.TextField(verbose_name='로그내용')),
                ('trace', models.TextField(blank=True, null=True, verbose_name='추적내용')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='발생일시')),
            ],
            options={
                'verbose_name': '로그내역',
                'verbose_name_plural': '로그내역',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
